/*****************************************************************//**
 * File: NegativeDeposit.h
 * Author: Leong Yah Xuan
 * Create Date: May 30, 2023
 * Update Date: May 30, 2023
 * Description: This C++ program is to implement two classes to handle exceptions.
 *********************************************************************/
#pragma once
#include <string>

 // Handling errors generated by the function deposit(double)
class NegativeDeposit {
public:
	// Constructor
	NegativeDeposit();
};
