/*****************************************************************//**
 * File: NegativeDeposit.cpp
 * Author: Leong Yah Xuan
 * Create Date: May 30, 2023
 * Update Date: May 30, 2023
 * Description: This C++ program is to implement two classes to handle exceptions.
 *********************************************************************/
#include "NegativeDeposit.h"

 /*****************************************************************//**
 * Intent: To handle errors generated by the function deposit(double).
 * Pre: The class NegativeDeposit must be well-defined.
 * Post: The function handles errors generated by the function deposit(double).
 *********************************************************************/
NegativeDeposit::NegativeDeposit() {};
